# Generated by Django 4.2.7 on 2023-12-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userprofile_date_joined_alter_userprofile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
