# Generated by Django 4.2.7 on 2023-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_done',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed ', 'Completed'), ('canceled ', 'Canceled')], default='in_progress', max_length=20),
        ),
    ]
